name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to HF
        env:
          # 【重要】GitHubに保存した名前に一言一句合わせます
          HF_TOKEN: ${{ secrets.HF_TOKEN }} 
        run: |
          git remote remove hf || true
          git remote add hf https://oauth:$HF_TOKEN@huggingface.co/spaces/horihorisoccer/sanfrecce-predictor
          git config --global http.postBuffer 524288000
          git push --force hf main